[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600
upload_speed = 921600
upload_port = COM4
monitor_port = COM4
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    bblanchon/ArduinoJson
    madhephaestus/ESP32Servo

; Build flags to increase available memory
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue